<?php
/**
 * Strings configuration.
 *
 * @package HivePress\Configs
 */

use HivePress\Helpers as hp;

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

return [

	// Common.
	'settings'                                  => esc_html__( 'Settings', 'hivepress' ),
	'display_noun'                              => esc_html_x( 'Display', 'noun', 'hivepress' ),
	'search_noun'                               => esc_html_x( 'Search', 'noun', 'hivepress' ),
	'search'                                    => esc_html__( 'Search', 'hivepress' ),
	'filter'                                    => esc_html__( 'Filter', 'hivepress' ),
	'sort_by'                                   => esc_html__( 'Sort by', 'hivepress' ),
	'keywords'                                  => esc_html__( 'Keywords', 'hivepress' ),
	'title'                                     => esc_html__( 'Title', 'hivepress' ),
	'name'                                      => esc_html__( 'Name', 'hivepress' ),
	'date'                                      => esc_html__( 'Date', 'hivepress' ),
	'status'                                    => esc_html__( 'Status', 'hivepress' ),
	'image'                                     => esc_html__( 'Image', 'hivepress' ),
	'images'                                    => esc_html__( 'Images', 'hivepress' ),
	'select_images'                             => esc_html__( 'Select Images', 'hivepress' ),
	'description'                               => esc_html__( 'Description', 'hivepress' ),
	'details'                                   => esc_html__( 'Details', 'hivepress' ),
	'emails'                                    => esc_html__( 'Emails', 'hivepress' ),
	'editing'                                   => esc_html__( 'Editing', 'hivepress' ),
	'submission'                                => esc_html__( 'Submission', 'hivepress' ),
	'moderation'                                => esc_html__( 'Moderation', 'hivepress' ),
	'expiration'                                => esc_html__( 'Expiration', 'hivepress' ),
	'expiration_period'                         => esc_html__( 'Expiration Period', 'hivepress' ),
	'expiration_date'                           => esc_html__( 'Expiration Date', 'hivepress' ),
	'default_fields'                            => esc_html__( 'Default Fields', 'hivepress' ),
	'free'                                      => esc_html__( 'Free', 'hivepress' ),
	'price'                                     => esc_html__( 'Price', 'hivepress' ),
	'overview'                                  => esc_html__( 'Overview', 'hivepress' ),
	'form'                                      => esc_html__( 'Form', 'hivepress' ),
	'filter_form'                               => esc_html__( 'Filter Form', 'hivepress' ),
	'sort_form'                                 => esc_html__( 'Sort Form', 'hivepress' ),
	'result_count'                              => esc_html__( 'Result Count', 'hivepress' ),
	'toolbar'                                   => esc_html__( 'Toolbar', 'hivepress' ),
	'menu'                                      => esc_html__( 'Menu', 'hivepress' ),
	'message'                                   => esc_html__( 'Message', 'hivepress' ),
	'completed'                                 => esc_html__( 'Completed', 'hivepress' ),
	'profile'                                   => esc_html__( 'Profile', 'hivepress' ),
	'pagination'                                => esc_html__( 'Pagination', 'hivepress' ),
	'storage'                                   => esc_html__( 'Storage', 'hivepress' ),
	'storage_period'                            => esc_html__( 'Storage Period', 'hivepress' ),
	'api_key'                                   => esc_html__( 'API Key', 'hivepress' ),
	'secret_key'                                => esc_html__( 'Secret Key', 'hivepress' ),
	'client_id'                                 => esc_html__( 'Client ID', 'hivepress' ),
	'client_secret'                             => esc_html__( 'Client Secret', 'hivepress' ),
	'redirect_url'                              => esc_html__( 'Redirect URL', 'hivepress' ),
	'app_id'                                    => esc_html__( 'App ID', 'hivepress' ),
	'authorization'                             => esc_html__( 'Authorization', 'hivepress' ),
	'return_to_my_account'                      => esc_html__( 'Return to My Account', 'hivepress' ),
	'my_account'                                => esc_html__( 'My Account', 'hivepress' ),
	'save_changes'                              => esc_html__( 'Save Changes', 'hivepress' ),
	'changes_have_been_saved'                   => esc_html__( 'Changes have been saved.', 'hivepress' ),
	'something_went_wrong'                      => esc_html__( 'Something went wrong.', 'hivepress' ),
	'user'                                      => esc_html__( 'User', 'hivepress' ),
	'all_users'                                 => esc_html__( 'All Users', 'hivepress' ),
	'registered_users'                          => esc_html__( 'Registered Users', 'hivepress' ),
	'columns_number'                            => esc_html_x( 'Columns', 'quantity', 'hivepress' ),
	'items_number'                              => esc_html_x( 'Number', 'quantity', 'hivepress' ),
	'actions'                                   => esc_html__( 'Actions', 'hivepress' ),
	'widgets'                                   => esc_html__( 'Widgets', 'hivepress' ),
	'primary_plural'                            => esc_html_x( 'Primary', 'plural', 'hivepress' ),
	'secondary_plural'                          => esc_html_x( 'Secondary', 'plural', 'hivepress' ),
	'related_plural'                            => esc_html_x( 'Related', 'plural', 'hivepress' ),
	'by_items_number'                           => esc_html_x( 'Item Count', 'sort order', 'hivepress' ),
	'by_name'                                   => esc_html_x( 'Name', 'sort order', 'hivepress' ),
	'by_date_added'                             => esc_html_x( 'Date Added', 'sort order', 'hivepress' ),
	'by_date_registered'                        => esc_html_x( 'Date Registered', 'sort order', 'hivepress' ),
	'by_title'                                  => esc_html_x( 'Title', 'sort order', 'hivepress' ),
	'by_random'                                 => esc_html_x( 'Random', 'sort order', 'hivepress' ),
	'sort_order'                                => esc_html_x( 'Order', 'sort', 'hivepress' ),
	'add_details_imperative'                    => esc_html_x( 'Add Details', 'imperative', 'hivepress' ),
	/* translators: %s: date. */
	'added_on_date'                             => esc_html__( 'Added on %s', 'hivepress' ),
	/* translators: %s: WooCommerce. */
	'ecommerce_product'                         => sprintf( esc_html__( '%s Product', 'hivepress' ), 'WooCommerce' ),
	/* translators: %s: token list. */
	'these_tokens_are_available'                => esc_html__( 'The following tokens are available: %s.', 'hivepress' ),
	/* translators: %s: extension name. */
	'extension_is_incompatible_with_core'       => esc_html__( '%s extension is incompatible with the current HivePress version, please update HivePress or deactivate it.', 'hivepress' ),
	/* translators: %s: terms URL. */
	'i_agree_to_terms_and_conditions'           => hp\sanitize_html( __( 'I agree to the <a href="%s" target="_blank">terms and conditions</a>', 'hivepress' ) ),
	/* translators: %s: field label. */
	'field_contains_invalid_value'              => esc_html__( '"%s" field contains an invalid value.', 'hivepress' ),
	/* translators: %s: field label. */
	'field_contains_too_many_values'            => esc_html__( '"%s" field contains too many values.', 'hivepress' ),

	// Listings.
	'listing'                                   => esc_html__( 'LiveEvent', 'wp-liveevents-enhancer' ),
	'listings'                                  => esc_html__( 'LiveEvents', 'wp-liveevents-enhancer' ),
	'all_listings'                              => esc_html__( 'All LiveEvents', 'wp-liveevents-enhancer' ),
	'related_listings'                          => esc_html__( 'Related LiveEvents', 'wp-liveevents-enhancer' ),
	/* translators: %s: Listings number. */
	'n_listings'                                => _n_noop( '%s LiveEvent', '%s LiveEvents', 'wp-liveevents-enhancer' ),
	/* translators: %s: Vendor name. */
	'listings_by_vendor'                        => esc_html__( 'LiveEvents by %s', 'wp-liveevents-enhancer' ),
	'featuring_of_listings'                     => esc_html__( 'Featuring of LiveEvents', 'wp-liveevents-enhancer' ),
	'featured_listings'                         => esc_html__( 'Featured LiveEvents', 'wp-liveevents-enhancer' ),
	'view_listings'                             => esc_html__( 'View LiveEvents', 'wp-liveevents-enhancer' ),
	'search_listings'                           => esc_html__( 'Search LiveEvents', 'wp-liveevents-enhancer' ),
	'no_listings_found'                         => esc_html__( 'No live events found.', 'wp-liveevents-enhancer' ),
	'listing_attributes'                        => esc_html__( 'LiveEvent Attributes', 'wp-liveevents-enhancer' ),
	'listing_category'                          => esc_html__( 'LiveEvent Category', 'wp-liveevents-enhancer' ),
	'listing_categories'                        => esc_html__( 'LiveEvent Categories', 'wp-liveevents-enhancer' ),
	'listing_search_form'                       => esc_html__( 'LiveEvent Search Form', 'wp-liveevents-enhancer' ),
	'listing_expiration'                        => esc_html__( 'LiveEvent Expiration', 'wp-liveevents-enhancer' ),
	'submit_listing'                            => esc_html__( 'Submit LiveEvent', 'wp-liveevents-enhancer' ),
	'renew_listing'                             => esc_html__( 'Renew LiveEvent', 'wp-liveevents-enhancer' ),
	'add_listing'                               => esc_html__( 'Add LiveEvent', 'wp-liveevents-enhancer' ),
	'view_listing'                              => esc_html__( 'View LiveEvent', 'wp-liveevents-enhancer' ),
	'edit_listing'                              => esc_html__( 'Edit LiveEvent', 'wp-liveevents-enhancer' ),
	'delete_listing'                            => esc_html__( 'Delete LiveEvent', 'wp-liveevents-enhancer' ),
	'report_listing'                            => esc_html__( 'Report LiveEvent', 'wp-liveevents-enhancer' ),
	'listing_submitted'                         => esc_html__( 'LiveEvent Submitted', 'wp-liveevents-enhancer' ),
	'listing_approved'                          => esc_html__( 'LiveEvent Approved', 'wp-liveevents-enhancer' ),
	'listing_rejected'                          => esc_html__( 'LiveEvent Rejected', 'wp-liveevents-enhancer' ),
	'listing_expired'                           => esc_html__( 'LiveEvent Expired', 'wp-liveevents-enhancer' ),
	'listing_renewed'                           => esc_html__( 'LiveEvent Renewed', 'wp-liveevents-enhancer' ),
	'listing_updated'                           => esc_html__( 'LiveEvent Updated', 'wp-liveevents-enhancer' ),
	'listing_reported'                          => esc_html__( 'LiveEvent Reported', 'wp-liveevents-enhancer' ),
	/* translators: %s: Listing title. */
	'listing_has_been_submitted'                => esc_html__( 'Thank you! Your live event "%s" has been submitted and will be reviewed as soon as possible.', 'wp-liveevents-enhancer' ),
	/* translators: %s: Listing title. */
	'listing_has_been_renewed'                  => esc_html__( 'Thank you! Your live event "%s" has been renewed and will appear at the top of the page.', 'wp-liveevents-enhancer' ),
	'listing_has_been_reported'                 => esc_html__( 'LiveEvent has been reported.', 'wp-liveevents-enhancer' ),
	'listings_page'                             => esc_html__( 'LiveEvents Page', 'wp-liveevents-enhancer' ),
	'listings_page_display'                     => esc_html__( 'LiveEvents Page Display', 'wp-liveevents-enhancer' ),
	'regular_listings_per_page'                 => esc_html__( 'Regular LiveEvents per Page', 'wp-liveevents-enhancer' ),
	'featured_listings_per_page'                => esc_html__( 'Featured LiveEvents per Page', 'wp-liveevents-enhancer' ),
	'related_listings_per_page'                 => esc_html__( 'Related LiveEvents per Page', 'wp-liveevents-enhancer' ),
	'mark_listing_as_verified'                  => esc_html__( 'Mark this live event as verified', 'wp-liveevents-enhancer' ),
	'make_listing_featured'                     => esc_html__( 'Make this live event featured', 'wp-liveevents-enhancer' ),
	'make_listings_featured'                    => esc_html__( 'Make live events featured', 'wp-liveevents-enhancer' ),
	'display_only_featured_listings'            => esc_html__( 'Display only featured live events', 'wp-liveevents-enhancer' ),
	'display_only_verified_listings'            => esc_html__( 'Display only verified live events', 'wp-liveevents-enhancer' ),
	'confirm_listing_deletion'                  => esc_html__( 'Are you sure you want to permanently delete this live event?', 'wp-liveevents-enhancer' ),
	'manually_approve_listings'                 => esc_html__( 'Manually approve new live events', 'wp-liveevents-enhancer' ),
	'allow_submitting_listings'                 => esc_html__( 'Allow submitting new live events', 'wp-liveevents-enhancer' ),
	'allow_reporting_listings'                  => esc_html__( 'Allow reporting live events', 'wp-liveevents-enhancer' ),
	'set_number_of_days_until_listing_expires'  => esc_html__( 'Set the number of days after which a live event expires.', 'wp-liveevents-enhancer' ),
	'set_number_of_days_until_listing_deleted'  => esc_html__( 'Set the number of days after which an expired live event is deleted.', 'wp-liveevents-enhancer' ),
	'set_date_on_which_listing_expired'         => esc_html__( 'Set a date on which the live event will expire.', 'wp-liveevents-enhancer' ),
	'set_date_on_which_listing_not_featured'    => esc_html__( 'Set a date on which the live event will lose featured status.', 'wp-liveevents-enhancer' ),
	'choose_page_that_displays_all_listings'    => esc_html__( 'Choose a page that displays all live events.', 'wp-liveevents-enhancer' ),
	'choose_page_with_listing_submission_terms' => esc_html__( 'Choose a page with terms that user has to accept before submitting a new live event.', 'wp-liveevents-enhancer' ),
	'provide_details_to_verify_listing_report'  => esc_html__( 'Please provide details that will help us verify that this live event violates the terms of service.', 'wp-liveevents-enhancer' ),
	'set_title_format_based_on_attributes'      => esc_html__( 'Set the title display format to generate titles based on attributes.', 'hivepress' ),

	// Vendors.
	'vendor'                                    => esc_html__( 'EventHost', 'wp-liveevents-enhancer' ),
	'view_vendor'                               => esc_html__( 'View EventHost', 'wp-liveevents-enhancer' ),
	'add_vendor'                                => esc_html__( 'Add EventHost', 'wp-liveevents-enhancer' ),
	'edit_vendor'                               => esc_html__( 'Edit EventHost', 'wp-liveevents-enhancer' ),
	'vendors'                                   => esc_html__( 'EventHosts', 'wp-liveevents-enhancer' ),
	'search_vendors'                            => esc_html__( 'Search EventHosts', 'wp-liveevents-enhancer' ),
	'no_vendors_found'                          => esc_html__( 'No event hosts found.', 'wp-liveevents-enhancer' ),
	'vendor_attributes'                         => esc_html__( 'EventHost Attributes', 'wp-liveevents-enhancer' ),
	'vendor_search_form'                        => esc_html__( 'EventHost Search Form', 'wp-liveevents-enhancer' ),
	'vendor_registered'                         => esc_html__( 'EventHost Registered', 'wp-liveevents-enhancer' ),
	'vendors_page'                              => esc_html__( 'EventHosts Page', 'wp-liveevents-enhancer' ),
	'regular_vendors_per_page'                  => esc_html__( 'EventHosts per Page', 'wp-liveevents-enhancer' ),
	'choose_page_that_displays_all_vendors'     => esc_html__( 'Choose a page that displays all event hosts.', 'wp-liveevents-enhancer' ),
	'display_vendors_on_frontend'               => esc_html__( 'Display event hosts on the front-end', 'wp-liveevents-enhancer' ),
	'display_only_verified_vendors'             => esc_html__( 'Display only verified event hosts', 'wp-liveevents-enhancer' ),
	'mark_vendor_as_verified'                   => esc_html__( 'Mark this event host as verified', 'wp-liveevents-enhancer' ),

	// Categories.
	'category'                                  => esc_html__( 'Category', 'hivepress' ),
	'categories'                                => esc_html__( 'Categories', 'hivepress' ),
	'all_categories'                            => esc_html__( 'All Categories', 'hivepress' ),
	'parent_category'                           => esc_html__( 'Parent Category', 'hivepress' ),
	'add_category'                              => esc_html__( 'Add Category', 'hivepress' ),
	'edit_category'                             => esc_html__( 'Edit Category', 'hivepress' ),
	'update_category'                           => esc_html__( 'Update Category', 'hivepress' ),
	'view_category'                             => esc_html__( 'View Category', 'hivepress' ),
	'search_categories'                         => esc_html__( 'Search Categories', 'hivepress' ),
	'no_categories_found'                       => esc_html__( 'No categories found.', 'hivepress' ),
	'select_category_imperative'                => esc_html_x( 'Select Category', 'imperative', 'hivepress' ),

	// Attributes.
	'attributes'                                => esc_html__( 'Attributes', 'hivepress' ),
	'attribute'                                 => esc_html__( 'Attribute', 'hivepress' ),
	'add_new_attribute'                         => esc_html_x( 'Add New', 'attribute', 'hivepress' ),
	'add_attribute'                             => esc_html__( 'Add Attribute', 'hivepress' ),
	'edit_attribute'                            => esc_html__( 'Edit Attribute', 'hivepress' ),
	'search_attributes'                         => esc_html__( 'Search Attributes', 'hivepress' ),
	'no_attributes_found'                       => esc_html__( 'No attributes found.', 'hivepress' ),

	// Attachments.
	'attachment'                                => esc_html__( 'Attachment', 'hivepress' ),
	'attachments'                               => esc_html__( 'Attachments', 'hivepress' ),
	'allow_file_attachments'                    => esc_html__( 'Allow file attachments', 'hivepress' ),
	'allowed_file_types'                        => esc_html__( 'Allowed File Types', 'hivepress' ),
];